### PR TITLE
Add ellipsis to artwork titles

### PR DESCRIPTION
**Pull request by isabelsang**
I think it looks a lot better now that all of the img cards are the same height but am debating if I should see if I can add the ellipsis after the second line of the title, since a lot of the artworks' titles are at least two lines long? Let me know what you think

ALSO: don't know why it says this PR has so many commits... all the changes are on the commit called "title truncated" so you can just look at that 

Before 
image

After
image

### CODE REVIEW

**Comment by indhu-gunda** [comment]
Did you base your branch off of something other than master because it looks like lots of the uploads stuff shows in your diff?

**Comment by indhu-gunda** [comment]
But also the uniformity looks really nice!! I don't really have a preference for 1 line or 2 lines.

**Comment by isabelsang** [comment]
> Did you base your branch off of something other than master because it looks like lots of the uploads stuff shows in your diff?

I based it off of my old branch query-api which is merged into master and deleted now.  I am not sure how I got the changes from PR #37 ?? The most recent thing I did was to do a `git pull` in master and then a `git merge master` in this ellipsis branch

**Comment by indhu-gunda** [comment]
> > Did you base your branch off of something other than master because it looks like lots of the uploads stuff shows in your diff?
> 
> I based it off of my old branch query-api which is merged into master and deleted now. I am not sure how I got the changes from PR #37 ?? The most recent thing I did was to do a `git pull` in master and then a `git merge master` in this ellipsis branch

That's so weird.

**Pull request merged**
